import "../ourdogs.html";
import "./sharedimports.js";
import elliePic from "../img/ellieheadshotcropped.jpg";
const ellieBioPic = document.getElementById("ellieBioPic");
ellieBioPic.src = elliePic;
import dukePic from "../img/dukeheadshotcropped.jpg";
const dukeBioPic = document.getElementById("dukeBioPic");
dukeBioPic.src = dukePic;
// import puppyTemp from "../img/temppuppythumb.jpg";
// const puppyThumb = document.getElementById("puppyTemp");
// puppyThumb.src = puppyTemp;
